compile_lin:
	g++ -g main.cpp lib/core.cpp branches/branches.cpp -o main 

compile_win:
	g++ -g main.cpp lib/core.cpp branches/branches.cpp -o main.exe 

debug:
	g++ -g main.cpp lib/core.cpp branches/branches.cpp -o main && ./main && rm main